#!/bin/bash

if [ `id -u` != 0 ];then
        echo ""
        echo -e "\e[31m Failed: Please Run this Script as root\e[0m\n"
        exit 1
fi

echo "RUNNING TASK 1 ......................."
echo "complex_abc_1245*abc!!!!!" | passwd --stdin root
echo "REBOOTING YOUR SYSTEM"
sleep 0
shutdown -r now
exit
